import os
import asyncio
import json
import logging
import re
import pandas as pd
from pydantic import BaseModel, Field, ValidationError, ConfigDict, model_validator
from openai import AsyncOpenAI
from dotenv import load_dotenv
import matplotlib.pyplot as plt

load_dotenv()
openrouter_client = AsyncOpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY"), 
)
JUDGE_MODEL = "anthropic/claude-3.5-sonnet"
INPUT_PATH = 'rag_final/rag_generated_articles_utility.json'
OUTPUT_PATH = 'rag_utility_evaluation_results_v1'

# --- 1. Define Structured Output Schemas ---
class EvalResult(BaseModel):
    rationale: str
    score: int
    
    # This config allows Pydantic to accept "Rationale" or "RATIONALE" as "rationale"
    model_config = ConfigDict(populate_by_name=True)

    @model_validator(mode="before")
    @classmethod
    def lowercase_keys(cls, data):
        if isinstance(data, dict):
            return {k.lower(): v for k, v in data.items()}
        return data

# --- 2. Robust JSON Extractor ---
def extract_json(text):
    """Shields the code from conversational 'filler' by isolating the JSON block."""
    try:
        # Find everything between the first '{' and the last '}'
        match = re.search(r'\{.*\}', text, re.DOTALL)
        return match.group(1) if match else text
    except Exception:
        return text


# --- 3. The Refined Judge Function ---
async def run_judge(prompt_template, **kwargs):
    full_prompt = prompt_template.format(**kwargs)
    
    try:
        response = await openrouter_client.chat.completions.create(
            model=JUDGE_MODEL,
            messages=[{"role": "user", "content": full_prompt + "\n\nReturn ONLY JSON."}],
            response_format={"type": "json_object"}, # Best for structured output
            temperature=0.0  # Deterministic output for evaluation
        )
        
        raw_content = response.choices[0].message.content
        cleaned_json = extract_json(raw_content)
        return EvalResult.model_validate_json(cleaned_json)
    except Exception as e:
        print(f"Error during LLM call: {e}")
        return EvalResult(rationale=f"Failed to evaluate: {str(e)}", score=0)


async def evaluate_entry(prompts, row):
    # --- 1. Basic Metadata Extraction ---
    paper_id = row.get('row_index')
    gen_model = row.get('generation_model')
    abstract = row.get('abstract', '')
    intro = row.get('introduction', '')
    article = row.get('rag_generated_news_article', '')
    # article = row.get('previous_generated_article', '')  # For evaluating previous version's retrieval utility
    pdf_source = row.get('citation', '')
    
    # 1. STRIP FILTER REASONS: Clean the snippets to avoid judge bias
    raw_snippets = row.get('snippets_used', [])
    clean_snippets_list = []
    for i, item in enumerate(raw_snippets):
        # Only keep text content that the generator actually used
        clean_snippets_list.append(
            f"--- Source {i+1} ---\n"
            f"Title: {item.get('title', 'N/A')}\n"
            f"URL: {item.get('link', 'N/A')}\n"
            f"Text: {item.get('snippet', '')}"
        )
    anchor_event = "\n\n".join(clean_snippets_list)

    logging.info(anchor_event)  

    logging.info(f"🔍 Evaluating Paper Index {paper_id} (Generated by: {gen_model})")

    tasks = [
        run_judge(prompts['1a_accuracy'], pdf_source=pdf_source, abstract=abstract, intro=intro, generated_content=article, anchor_event=anchor_event),
        run_judge(prompts['1b_technical_distortion'], abstract=abstract, intro=intro, generated_content=article, anchor_event=anchor_event),
        run_judge(prompts['2a_novelty_emphasis'], abstract=abstract, intro=intro, generated_content=article, anchor_event=anchor_event), 
        run_judge(prompts['2b_scientific_significance'], abstract=abstract, intro=intro, generated_content=article, anchor_event=anchor_event),
        run_judge(prompts['3a_engagement_hook_strength'], generated_content=article, anchor_event=anchor_event),
        run_judge(prompts['3b_logical_attractiveness'], generated_content=article),
        run_judge(prompts['3c_call_to_action'], pdf_source=pdf_source, generated_content=article),
        run_judge(prompts['4a_rag_relevance'], abstract=abstract, intro=intro, anchor_event=anchor_event),
        run_judge(prompts['4b_rag_utility'], generated_content=article, anchor_event=anchor_event),
    ]
    
    results = await asyncio.gather(*tasks)
    
    # --- 5. Return Structured Results ---
    return {
        "paper_index": paper_id,
        "generation_model": gen_model,
        "judge_model": JUDGE_MODEL,
        # Mapping results to keys (ensure indices match task list above)
        "1a_accuracy_score": results[0].score,
        "1a_accuracy_rationale": results[0].rationale,
        "1b_technical_distortion_score": results[1].score,
        "1b_technical_distortion_rationale": results[1].rationale,
        "2a_novelty_emphasis_score": results[2].score,
        "2a_novelty_emphasis_rationale": results[2].rationale,
        "2b_scientific_significance_score": results[3].score,
        "2b_scientific_significance_rationale": results[3].rationale,
        "3a_engagement_hook_strength_score": results[4].score,
        "3a_engagement_hook_strength_rationale": results[4].rationale,
        "3b_logical_attractiveness_score": results[5].score,
        "3b_logical_attractiveness_rationale": results[5].rationale,
        "3c_call_to_action_score": results[6].score,
        "3c_call_to_action_rationale": results[6].rationale,
        "4a_rag_relevance_score": results[7].score,
        "4a_rag_relevance_rationale": results[7].rationale,
        "4b_rag_utility_score": results[8].score,
        "4b_rag_utility_rationale": results[8].rationale,
    }


# --- 5. Batch Process Runner ---
async def main():
    metric_keys = ['1a_accuracy', '1b_technical_distortion', '2a_novelty_emphasis', '2b_scientific_significance', '3a_engagement_hook_strength', '3b_logical_attractiveness', '3c_call_to_action', '4a_rag_relevance', '4b_rag_utility']
    loaded_prompts = {}
    logging.info("Loading prompt templates...")

    for key in metric_keys:
        with open(f"prompts/rag_with_evolving_rubrics/{key}.txt", 'r') as f:
            loaded_prompts[key] = f.read()

    # Load your generated articles
    with open(INPUT_PATH, 'r') as f:
        data = json.load(f)

    print(f"Starting evaluation of {len(data)} entries using {JUDGE_MODEL}...")
    
    # Execute evaluation for all entries in the file
    eval_tasks = [evaluate_entry(loaded_prompts, row) for row in data]
    final_results = await asyncio.gather(*eval_tasks)
    
    # Save to CSV for easy comparison
    df = pd.DataFrame(final_results)
    df.to_csv(f'rag_final/{OUTPUT_PATH}.csv', index=False)
    
    # Save to JSON for full detail (rationales)
    with open(f'rag_final/{OUTPUT_PATH}.json', 'w', encoding='utf-8') as f:
        json.dump(final_results, f, indent=4)

    print(f"Success! Scores saved to rag_final/{OUTPUT_PATH}.csv and rag_final/{OUTPUT_PATH}.json")


# --- 6. Visualization Function ---
def plot_model_comparison(file_path, output_name):
    """
    Groups evaluation data by model, calculates means, and generates a bar chart.
    
    Args:
        file_path (str): Path to your .json or .csv results file.
        output_name (str): The filename for the exported image.
    """
    # 1. Load Data
    if file_path.endswith('.json'):
        with open(file_path, 'r') as f:
            data = json.load(f)
        df = pd.DataFrame(data)
    else:
        df = pd.read_csv(file_path)

    # 2. Extract Score Columns
    score_cols = [col for col in df.columns if col.endswith('_score')]

    # 3. Calculate Averages
    avg_scores = df.groupby('generation_model')[score_cols].mean()

    # 4. Clean Labels for the Legend (e.g., '1a_accuracy_score' -> 'Accuracy')
    clean_labels = {
        col: col.split('_', 1)[1].replace('_score', '').replace('_', ' ').title() 
        for col in score_cols
    }
    avg_scores = avg_scores.rename(columns=clean_labels)

    # 5. Plotting
    plt.figure(figsize=(14, 8))
    ax = avg_scores.plot(kind='bar', figsize=(14, 8), width=0.8, edgecolor='white')

    # Add visual refinements
    plt.title('Performance Comparison Across Generation Models', fontsize=16, pad=25)
    plt.ylabel('Average Rating (1-5)', fontsize=12)
    plt.xlabel('Model Name', fontsize=12)
    plt.xticks(rotation=30, ha='right')
    plt.ylim(0, 5.5)
    plt.grid(axis='y', linestyle='--', alpha=0.3)
    
    # Position legend to the right of the chart
    plt.legend(title='Evaluation Metrics', bbox_to_anchor=(1.02, 1), loc='upper left', frameon=False)

    # 6. Save and Export
    plt.tight_layout()
    plt.savefig(output_name, dpi=300)
    print(f"Success: Chart saved to {output_name}")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(main())